### ISSUE TITLE
Error connectionFactory must be specified

### ISSUE THREAD

**Issue by sabbane** [monodot/camel-demos#2]
In case the version of "camel-spring-boot-dependencies" is set to v3.1.0 the program crahes with the following error message:

```
Caused by: java.lang.IllegalArgumentException: connectionFactory must be specified
	at org.apache.camel.util.ObjectHelper.notNull(ObjectHelper.java:152) ~[camel-util-3.1.0.jar:3.1.0]
...
```
The same error occured with the version v3.0.0 in case an endpoint is declared. So e.g. adding the following line just before the routes definitions:

`Endpoint endpoint = endpoint("jms:queue:HELLO.WORLD");`

will cause the exception:

> Caused by: java.lang.IllegalArgumentException: connectionFactory must be specified
> 	at org.apache.camel.util.ObjectHelper.notNull(ObjectHelper.java:152) ~[camel-util-3.0.0.jar:3.0.0]

**Comment by bessalahAmar** [comment]
did you find any solution for that other then creating manually the connectionFactory ?

**Comment by monodot** [comment]
Thanks for raising this. It seems there was an issue with the version of Camel/Spring Boot used in the example. I've upgraded the repo to Camel 3.4.2, and added some guidance in the README on starting an ActiveMQ Artemis instance (in a container). It's working now but please re-open if you still have an issue.
